server:
  port: 8080

codex:
  workspace:
    path: ./workspace
  ai:
    url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
    apiKey: ${LLM_API_KEY}
    model: "qwen3.7-plus"
  agent:
    max-step: 5

spring:
  profiles:
    active: local
  jackson:
    time-zone: GMT+8
ai:
  project:
    path: D:/traeproject/demo01




